name: CI
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build:
    name: 'Build Flow'
    uses: Orkuncakilkaya/dx-team-toolkit/.github/actions/build-typescript-project@v1
    with:
     skipLinter: true
     skipTests: true
     skipTypeChecking: true