name: CI
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build:
    name: 'Build Flow'
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        uses: Orkuncakilkaya/dx-team-toolkit/.github/actions/build-typescript-project@v1
        with:
          skipTypeChecking: true
          skipTests: true
          skipLinter: true
      - name: "Release"
        uses: Orkuncakilkaya/dx-team-toolkit/.github/actions/release-typescript-project@v1
        with:
         skipLinter: true
         skipTests: true
         skipTypeChecking: true