name: Release
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build:
    name: 'Release Flow'
    runs-on: ubuntu-latest
    steps:
      - name: "Release"
        uses: Orkuncakilkaya/dx-team-toolkit/.github/actions/release-typescript-project@v1
        with:
          skipTypeChecking: true
          skipTests: true
          skipLinter: true